apiVersion : apps/v1
kind: ReplicaSet
metadata:
    name: myrs
spec:
   replicas: 3
   selector:
      matchExpressions:
      - key: app
        operator: In
        values: [myapp]
      - key: env
        operator: NotIn
        values: [dev]
   template:
     metadata:
        labels:
           app: myapp
     spec:
        containers:
        - name: con1
          image: nginx:latest
          ports:
          - containerPort: 80
#        nodeName: i-06ca7deeda5df79ff
---
apiVersion: v1
kind: Service
metadata:
  name: myrc-svc
spec:
  ports:
  - port: 80
    nodePort: 30123
  selector:
    app: myapp
  type: NodePort
